### ISSUE TITLE
Please remove copyrighted content or set proper attribution

### ISSUE THREAD

**Issue by napulen** [X-lab2017/X-lab2017.github.io#3]
Hi, 

The content displayed at http://www.x-lab.info/publication/ belongs to my site.

I take it that you probably borrowed it temporarily while making a site template, but please kindly remove this content. 

Best,
Néstor

**Comment by will-ww** [comment]
Sure, thanks for your information. We will do it right now.

**Comment by leofang327** [comment]
thanks for your kind remind, we have already removed the content.

**Comment by napulen** [comment]
Appreciated. Thanks!
